name: github-action

on: [push, pull_request] 

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.7']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}
    - name: install postgres (linux)
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-14
        export PATH=$PATH:/usr/lib/postgresql/14/bin
        which pg_ctl
        echo "/usr/lib/postgresql/14/bin" >> $GITHUB_PATH
      if: matrix.os == 'ubuntu-latest'
    - name: install postgres (macos)
      run: |
        brew update
        brew install postgresql@14
        export PATH=$PATH:`brew --prefix`/bin
        which pg_ctl
        echo "$(brew --prefix)/bin" >> $GITHUB_PATH
      if: matrix.os == 'macos-latest'
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
